### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by alexandrugavril** [alexandrugavril/CamiAndroidApp#8]
The application should have a Login Page with Username and Password.

If the login user is a doctor, the doctor page should be the next page.
If the login user is a pacient, the pacient page should be shown. 
If the login fails, a message should inform the user.

**Comment by asorici** [comment]
Login page must offer a visual queue of the reason it failed (since every element is controlled by us - i.e. we know what the password is).
  - unknown username: user input field turns red and the message "Unknown user: <input username>" is displayed
  - wrong password: password input field turns red and the message "Wrong password for user <input username>." is displayed

The fields return to their normal styling when they regain focus after a warning message.

**Comment by alexandrugavril** [comment]
Usually telling why the login has failed has some security issues, since knowing that the password for that user is wrong usually tells you that the user actually exist.

**Comment by asorici** [comment]
Agreed. Please just add a generic message of the form: "wrong username or password".
The message must be added in the translations dict.
